### ISSUE TITLE
Bindings for other languages?

### ISSUE THREAD

**Issue by rudimk** [ybur-yug/gkv#5]
This looks awesome! However, I'm not much of a Ruby user. Any thoughts on creating bindings for, say, Python or Javascript?

Off the top of my head, just to get started, I could use a bridge in Python that is capable of calling Ruby functions. Could use that to hook into gkv. Not sure about performance, though.

**Comment by ishankhare07** [comment]
we can write an independent python version itself

**Comment by rudimk** [comment]
Yep. That can be done too. 

Btw, here you are. Very simple stuff. https://github.com/rudimk/pyGKV

**Comment by rudimk** [comment]
And in that case, I'm all for writing independent versions for Javascript and Julia too.

**Comment by ishankhare07** [comment]
@rudimk can we pair for a pure python based implementation for this?

**Comment by rudimk** [comment]
Absolutely.

**Comment by ybur-yug** [comment]
This is on the roadmap for v0.3! So if you'd like to fork and work on the feature and have it patched in I will gladly assist @rudimk and @ishankhare07

**Comment by ishankhare07** [comment]
@ybur-yug https://github.com/ishankhare07/PyGKV purely written in python, no dependencies, works out-of-the box

**Comment by ybur-yug** [comment]
@ishankhare07 If you'd like I can package it up as a true pip package and add in the YAML dumps/loads so you can have true typing and not just string store.

**Comment by ishankhare07** [comment]
@ybur-yug if you don't mind, you can guide me a little, i want to learn by doing

**Comment by ybur-yug** [comment]
Absolutely. I would start by packaging it to this protocol.
https://packaging.python.org/en/latest/distributing.html

Once you get that done I can help with typing after :)

**Comment by ishankhare07** [comment]
@ybur-yug don't know why but i'm getting an
```error: HTTP Error 400: Binary wheel for an unsupported platform```

**Comment by ishankhare07** [comment]
ok i made it
https://pypi.python.org/pypi?:action=display&name=pygkv&version=0.1.2

**Comment by ybur-yug** [comment]
Awesome! So now you've got a bit of an open book on how to handle typing. Obviously right now since you are storing blobs via hash-object, they will be fed in and read out as strings. This is suboptimal as we generally like to have types in programming.

Solutions: JSON and YAML are both reasonable standards that have cross-compatibility across languages and understand their types for parsing. In the Ruby implementation I am using YAML, but JSON would be acceptable as well (I chose YAML for a variety of reasons not worth writing about). So, you would want to load the read-out data (cat-file) with YAML/JSON.load and the written data (hash-object) with YAML/JSON.dumps just like in the ruby source.

Does this make sense? There are other ways but they are much more hacky/open to vulnerability
